#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

public typealias AppReceipt = ContentInfo<SignedData<InAppReceiptPayload>>

extension AppReceipt {
    /// The environment in which the receipt was generated.
    public var environment: InAppReceiptPayload.Environment {
        payload.environment
    }

    /// The app's bundle identifier.
    ///
    /// Uniquely identifies the application that generated the receipt.
    public var bundleIdentifier: String {
        payload.bundleIdentifier
    }

    /// The app's version number.
    ///
    /// The current version of the app at the time the receipt was generated.
    public var appVersion: String {
        payload.appVersion
    }

    /// The version of the app that was originally purchased.
    ///
    /// This represents the version of the app when the user first purchased it.
    public var originalAppVersion: String? {
        payload.originalAppVersion
    }

    /// The date of the app that was originally purchased.
    ///
    /// The date when the user first purchased the app.
    public var originalPurchaseDate: Date? {
        payload.originalPurchaseDate
    }

    /// All in-app purchases in this receipt.
    ///
    /// Returns an array of ``InAppPurchase`` objects representing all purchases included in the receipt.
    public var purchases: [InAppPurchase] {
        payload.purchases
    }

    /// All auto-renewable subscription purchases in this receipt.
    ///
    /// Returns an array of ``InAppPurchase`` objects that are auto-renewable subscriptions.
    public var autoRenewablePurchases: [InAppPurchase] {
        purchases.filter { $0.isRenewableSubscription }
    }

    /// All currently active auto-renewable subscription purchases in this receipt.
    ///
    /// Returns an array of ``InAppPurchase`` objects that are auto-renewable subscriptions
    /// and are currently active as of the current date.
    public var activeAutoRenewableSubscriptionPurchases: [InAppPurchase] {
        purchases
            .filter {
                $0.isRenewableSubscription && $0.isActiveAutoRenewableSubscription(forDate: Date())
            }
    }

    /// The date that the app receipt expires.
    ///
    /// For most apps, this is the expiration date of the last auto-renewable subscription.
    public var expirationDate: Date? {
        payload.expirationDate
    }

    /// Indicates whether the receipt contains any purchases.
    ///
    /// Returns `true` if any purchases exist, `false` otherwise.
    public var hasPurchases: Bool {
        purchases.count > 0
    }

    /// Indicates whether the receipt contains any active auto-renewable purchases.
    ///
    /// Returns `true` if any active auto-renewable subscription purchases exist, `false` otherwise.
    public var hasActiveAutoRenewablePurchases: Bool {
        activeAutoRenewableSubscriptionPurchases.count > 0
    }

    /// The date the receipt was created.
    ///
    /// The date and time when the receipt was generated by Apple.
    public var creationDate: Date {
        payload.creationDate
    }

    /// The app's age rating.
    ///
    /// A string value representing the age rating for the app.
    public var ageRating: String? {
        payload.ageRating
    }
}

extension AppReceipt {
    /// The decoded receipt payload.
    ///
    /// Extracts and returns the in-app receipt payload data from the receipt structure.
    public var payload: InAppReceiptPayload {
        guard let payload = content.encapContentInfo.eContent else {
            fatalError("Invalid receipt payload")
        }

        return payload
    }

    /// The raw payload data.
    ///
    /// Returns the raw bytes of the receipt payload in its original encoded format.
    public var payloadRawData: Data {
        guard
            let payload = content.encapContentInfo.eContentRaw,
            !payload.bytes.isEmpty
        else {
            fatalError("Invalid receipt payload")
        }

        return Data(payload.bytes)
    }

    /// Indicates whether the receipt has a valid structure.
    ///
    /// Returns `true` if the receipt contains a valid payload, signer information, and certificates,
    /// `false` otherwise.
    public var hasValidStructure: Bool {
        guard content.encapContentInfo.eContent != nil,
            !content.signerInfos.isEmpty,
            !content.certificates.isEmpty
        else {
            return false
        }

        return true
    }
}
